modify buildme_dependencies to use latest libcirlce

diff --git a/buildme b/buildme
--- a/buildme
+++ b/buildme
@@ -16,8 +16,6 @@ rm -rf build
 mkdir -p build
 cd build
 
-which pkg-config
-
 export PKG_CONFIG_PATH="${installdir}/lib/pkgconfig"
 
 # TODO: avoid this step
@@ -31,8 +29,10 @@ export LDFLAGS="-Wl,-rpath,${topdir}/install/lib -L${topdir}/install/lib -lcircl
 ../configure \
   --prefix=$installdir \
   --disable-silent-rules \
-  --with-libdtcmp=$installdir
-
-make VERBOSE=1
-
+  --with-libdtcmp=$installdir && \
+make VERBOSE=1 && \
 make VERBOSE=1 install
+if [ $? -ne 0 ] ; then
+  echo "failed to configure, build, or install file utils"
+  exit 1
+fi
