add dtar to buildme and buildme_dependencies

diff --git a/buildme b/buildme
--- a/buildme
+++ b/buildme
@@ -28,7 +28,7 @@ OPT="-g -O0"
 
 installdir=`pwd`/install
 
-mkdir ${installdir}/bin
+mkdir -p ${installdir}/bin
 
 # build libbayer
 pushd libbayer
@@ -92,7 +92,17 @@ pushd drm
   cp drm ${installdir}/bin
 popd
 
-# build dtar command
+# build dtar
+pushd dtar/src
+  mpicc ${OPT} -o dtar \
+    copy.c helper.c dtar.c \
+    -I${installdir}/include -L${installdir}/lib -Wl,-rpath,${installdir}/lib -lcircle -larchive -llwgrp -ldtcmp -lbayer
+  if [ $? -ne 0 ]; then
+    echo "failed to build dtar"
+    exit 1
+  fi
+  cp dtar ${installdir}/bin
+popd
 
 # build dfind command
 #pushd dfind
@@ -104,6 +114,18 @@ popd
 #
 #  cp dfind ${installdir}/bin
 #popd
+
+# build dcmp command
+pushd dcmp
+  mpicc ${OPT} -o dcmp dcmp.c \
+    -I${installdir}/include \
+    -L${installdir}/lib -Wl,-rpath,${installdir}/lib -lcircle -llwgrp -ldtcmp -lbayer
+  if [ $? -ne 0 ]; then
+    echo "failed to build dcmp"
+    exit 1
+  fi
+  cp dcmp ${installdir}/bin/.
+popd
 
 # build dcp command
 mkdir -p dcp
@@ -125,6 +147,7 @@ pushd dcp
       export PKG_CONFIG_PATH="${installdir}/lib/pkgconfig"
       export CFLAGS="-g -O0"
       ./configure --prefix=$installdir --disable-silent-rules
+      #./configure --prefix=$installdir --disable-silent-rules --disable-xattr
     fi
 
     # build dcp command
@@ -140,16 +163,4 @@ pushd dcp
       cp dcp ${installdir}/bin
     popd
   popd
-popd
-
-# build dcmp command
-pushd dcmp
-  mpicc ${OPT} -o dcmp dcmp.c \
-    -I${installdir}/include \
-    -L${installdir}/lib -Wl,-rpath,${installdir}/lib -lcircle -llwgrp -ldtcmp -lbayer
-  if [ $? -ne 0 ]; then
-    echo "failed to build dcmp"
-    exit 1
-  fi
-  cp dcmp ${installdir}/bin/.
 popd
diff --git a/buildme_dependencies b/buildme_dependencies
--- a/buildme_dependencies
+++ b/buildme_dependencies
@@ -55,6 +55,12 @@ if [ ! -d dtcmp.git ]; then
   exit 1
 fi
 
+# clean out our autotools install directory
+toolsdir=`pwd`/autotools/install
+
+# add autotools install bin to our path
+export PATH=${toolsdir}/bin:$PATH
+
 # build dependencies
 pushd libcircle.git
   export CFLAGS=${OPT}
@@ -89,6 +95,22 @@ pushd dtcmp.git
   make install
   if [ $? -ne 0 ]; then
     echo "failed to configure, build, or install libdtcmp"
+    exit 1
+  fi
+popd
+
+rm -rf libarchive-3.1.2
+cp ../dtar/libarchive-3.1.2.tar.gz .
+tar zxvf libarchive-3.1.2.tar.gz
+pushd libarchive-3.1.2
+#  make distclean
+#  ./autogen.sh
+  export CFLAGS=${OPT}
+  ./configure --prefix=${installdir} && \
+  make && \
+  make install
+  if [ $? -ne 0 ]; then
+    echo "failed to configure, build, or install libarchive"
     exit 1
   fi
 popd
