add makedist script, update buildme for new --with-dtcmp option

diff --git a/makedist b/makedist
--- a/makedist
+++ b/makedist
@@ -26,13 +26,29 @@ export CC=mpicc
 export CFLAGS="-I${topdir}/src/common -DDCOPY_USE_XATTRS"
 export LDFLAGS="-Wl,-rpath,${topdir}/install/lib -L${topdir}/install/lib -lcircle"
 
+make distclean
+
 ../configure \
   --prefix=$installdir \
   --disable-silent-rules \
-  --with-dtcmp=$installdir && \
-make VERBOSE=1 && \
-make VERBOSE=1 install
+  --with-dtcmp=$installdir
+#../configure \
+#  --prefix=/usr/local/fileutils
 if [ $? -ne 0 ] ; then
-  echo "failed to configure, build, or install file utils"
+  echo "failed to configure"
   exit 1
 fi
+
+make dist
+if [ $? -ne 0 ] ; then
+  echo "failed to make dist"
+  exit 1
+fi
+
+make distcheck
+if [ $? -ne 0 ] ; then
+  echo "failed to make distcheck"
+  exit 1
+fi
+
+mv *.tar.gz ../.
